---
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
        ignore: 'order-alphabetical,box-sizing'
files:
    ignore:
        - 'node_modules/*'
        - 'src/generated/*'
        - 'src/public/main.js'
        - 'dist/main.js'
        - 'webroot/bower_components/*'
